### ISSUE TITLE
[Question] What's the toll on a local desktop computer?

### ISSUE THREAD

**Issue by LaughterOnWater** [teticio/audio-diffusion#1]
Hello!

I've installed and can use Stable Diffusion on my desktop computer.
Setup:
Windows 10 pro
Nvidia Quadro M4000 8GB GDDR5
AMD Ryzen 7 5800X 8-Core Processor, 4601 Mhz, 8 Core(s), 16 Logical Processor(s)
32GB RAM 
Python/powershell install of AUTOMATIC1111/stable-diffusion-webui with Gradio WebUI 
Python 3.10.7 for Windows 1
Renders are slow, but achievable in about 90 seconds for 512x1020. 

It works great.

I'd like to install audio-diffiusion, but am concerned about render times/file sizes.
Given a library of various genres, how likely is it that my local computer can handle this?
If I had a thousand songs to train in various genres/styles, how long would it take?
Would my computer pretty much be tied up for that time?
How long does it take to render a prompt based on trained input?

If you have a link to where all these answers are already, I'd be grateful.

Thanks for your time.

Chris

**Comment by teticio** [comment]
I think the best thing is to try it... You will probably have to limit the batch_size to 1 for training (also change gradient_accumulation_steps to 16 to compensate).
