### ISSUE TITLE
Mind if I share?

### ISSUE THREAD

**Issue by corranmac** [teticio/audio-diffusion#11]
Hi Robert,

Your results so far are amazing, so much better than any other I've seen so I'm very surprised this repo hasn't blown up in popularity. Mind if I share this with the LAOIN community? I feel like they'd find it really interesting. They're currently working on a huge audio dataset, so I wonder if there could be potential to use it, alongside implementing some sort of text guidance.

You definetely deserve loads of recognition for this but I'd understand if you're happy its not well known yet, if that lets you develop it quietly without too much interference!

Otherwise, I'm looking forward to seeing how far you can take these methods,

Cheers

**Comment by teticio** [comment]
Of course I don't mind, please go ahead!! The more the merrier! Thanks for the words of encouragement. I have been having a lot of fun with this repo and I feel there is still more to come.
