### ISSUE TITLE
Tiny thing but...  0.1 not .1

### ISSUE THREAD

**Issue by twobob** [teticio/audio-diffusion#12]
![image](https://user-images.githubusercontent.com/915232/197557060-13381285-a13a-4e1a-b880-0b261fb6ffaf.png)

[number does not accept .1  only 0.1](https://github.com/teticio/audio-diffusion/pull/13)

That's why the slider don't work.

**Comment by twobob** [comment]
Added pull

**Comment by teticio** [comment]
Thanks!!!
