### ISSUE TITLE
Question about add_noise

### ISSUE THREAD

**Issue by 980202006** [teticio/audio-diffusion#15]
I have a batch of data, and the value range of clean_image is [0,1]. Do I need to modify add_noise to adapt to the value range of clean_image?

**Comment by 980202006** [comment]
I am training this model on dry vocal. Considering the accuracy, I changed the image data storage to float. My mel original value range is 1~-11 (hop size of 240). I normalized it before inputting it into the model. , normalize the value range to 0~1.The following is my loss curve, as well as image and audio.

**Comment by 980202006** [comment]
Could you share the tensorboard of "teticio/audio-diffusion-ddim-256"? I am training the ddim model on dry vocal.

**Comment by teticio** [comment]
Weird, not sure why the tensorboard didn't push to the hub. I have pushed it by hand now https://huggingface.co/teticio/audio-diffusion-ddim-256/tensorboard. Regarding your question, I would need to know what you mean by data - the images are expected to be in the range 0, 255 and are normalized accordingly.

**Comment by 980202006** [comment]
Thank you! This tensorboard is very helpful for me.
I have a batch of mostly dry singing data. I use the bigvgan scheme to extract its audio features as input data. The audio feature range is around [-10,1]. At present, I am training the ddpm model, and there is audible sound at 10epoch, but the same configuration (except num_train_steps=50) ddim is difficult to converge, even at 10epoch, it is still meaningless noise.

**Comment by teticio** [comment]
I think you need to train with more steps - I used 1000 if I remember right. You can do inference with much fewer steps (like 50).
