### ISSUE TITLE
How to run this scripts in linux?

### ISSUE THREAD

**Issue by manman25** [teticio/audio-diffusion#16]
![image](https://user-images.githubusercontent.com/20472753/204322338-1883e213-f504-4204-92f9-be546d8faf87.png)

Hi! I'm running the app.py in the Linux, and it shows that running on a local URL. 
It this right? and I want to know how many minutes this should be running this script.

**Comment by manman25** [comment]
Or may you tell me a more detail tutor for using these codes in Linux?

**Comment by teticio** [comment]
You must be missing a `\` at the end of the previous line. `--output_dir` is a parameter and should be passed to the command, not sent as a separate command...
