### ISSUE TITLE
Starting Point for Dataset

### ISSUE THREAD

**Issue by JousterL** [teticio/audio-diffusion#17]
First, love the work, been playing around with it for the past day or two.

I saw in another issue that you mentioned needing to play around to find a happy medium in terms of # of samples, sample length, dataset totals, epochs, etc... but I'm hoping that a rough rubric could come out, as I've struggled to get anything meaningful from a few different approaches.

My latest approach was to take 5 second 'clips' every 10% of a song, since my corpus for generation is rather small (~50 songs). But I'm struggling to understand the relationship between number of samples and epochs... I.E. you mentioned that getting 100 epochs across 20K samples was positive. Would that be a relatively linear relationship e.g. since I have 500 samples (2.5%) I need to multiply my epoch total by an equivalent scaling factor e.g. 10000 epochs? Or is there no clear relationship and I just need to find more samples to be closer to the 20K target?

Thank you again for any advice you can provide.

**Comment by teticio** [comment]
Hi there.

To be honest I don't know the answer, I can only say what I have done and speculate a little. My hope is that more people like you will try with different datasets and help us all understand better!

I have found that it works best with electronic music and my guess is that it is useful to have entire songs chopped up into samples. I think of these as "augmentations" in the same way as you might use images taken from different angles to train an image model.

I can tell you for sure that trying to compensate for lacking data with more epochs will definitely not work well. The model will just overfit to the little data it has and, at best, just memorize it. For reference, I used about 400 songs - perhaps you could slice the 50 songs into 5 second samples starting from 0 seconds, 1 seconds, .... 4 seconds. That might help.

**Comment by JousterL** [comment]
Thanks for the clear response! That definitely helps, in that I didn't think about overlapping samples being 'acceptable' from a dataset perspective. I'll definitely try that.

I am curious how the Mel spectrograms are generated in a 'naive' approach (I.E. when I was first playing around with it, I wasn't careful and fed Mel the entire audio file, but with your suggested parameters of 64x64 resolution). Does it split the song up into equivalent # of samples, and my custom scripting/sample creation is duplicative, or is it compressing a 3.5 minute song into a tiny window and compressing away all of the detail?

**Comment by teticio** [comment]
The script automatically chops it up into slices. If you want to do the augmentation I suggested, you could create additional input files by using something like `ffmpeg` to chop off the first 1 second, 2 second etc. But take into account the length in time your 64x64 spectrogram converts back to (use the `test_mel` notebook to play around with the parameters before training any models). I warn you that 64x64 will not get great results. You might want to try training on Colab - there is a starter notebook for this `train_model` although I haven't adapted it to push the models to hub (hint: install git lfs on Colab).

**Comment by JousterL** [comment]
Thank you for the guidance! I'll definitely play around and explore expanded spectrograms.
