### ISSUE TITLE
train_vae.py report error 'gpu' is not a valid DistributedType

### ISSUE THREAD

**Issue by zhangaixi2008** [teticio/audio-diffusion#18]
When I test train_vae.py with the command "python scripts/train_vae.py --dataset_name data/audio-diffusion-256 --batch_size 2 --gradient_accumulation_steps 12", the following error occurs:
ValueError: 'gpu' is not a valid DistributedType.
Any suggestion to solve it ? Thanks.

**Comment by teticio** [comment]
Do you have a GPU on your machine? If not, the training will be way too slow. Nevertheless, you can delete / change the line `accelerator` in `config/ldm_autoencoder_kl.yaml`. If that isn't it, what version of `pytorch_lightning` do you have installed?

**Comment by zhangaixi2008** [comment]
I have GPU. I follow the README exactly, with pytorch-lightning 1.7.7 and torch 1.13.0.

**Comment by teticio** [comment]
Can you check that your GPU is accessible when you run the script? Add these lines:
```
import torch

print('Number of GPUs available', torch.cuda.device_count())
```
and check that there is at least one?

**Comment by zhangaixi2008** [comment]
It works now. The reason is still because of a wrong version pytorch-lightning. Sorry for that~

**Comment by teticio** [comment]
Great!
