### ISSUE TITLE
Couldn't cast because column names don't match

### ISSUE THREAD

**Issue by mattgallivan** [teticio/audio-diffusion#2]
I'm attempting to run the command

`python audio_to_images.py --resolution 64 --hop_length 1024 --input_dir data-in --output_dir data-out`

on a directory of .wav files, but I keep receiving the error

```
ValueError: Couldn't cast
__index_level_0__: null
-- schema metadata --
pandas: '{"index_columns": ["__index_level_0__"], "column_indexes": [{"na' + 310
to
{'image': Image(decode=True, id=None), 'audio_file': Value(dtype='string', id=None), 'slice': Value(dtype='int16', id=None)}
because column names don't match
```

Is there a specific filetype for the audio I should be using?

**Comment by teticio** [comment]
Yes, a bit of a cryptic error I'm afraid. Coincidentally, I put a more user friendly warning for when no suitable files are found. It should find wav files fine - I just tested it and it works. Can you double check they are valid and in the directory (and not in a subddirectory)?

**Comment by mattgallivan** [comment]
Ah you're right! There was an issue with the path in WSL 2. Thanks!
