### ISSUE TITLE
diffusers v-0.12.0 causes import issues

### ISSUE THREAD

**Issue by shiehn** [teticio/audio-diffusion#23]
FYI: diffusers v-0.12.0 causes import issues.  I didn't investigate a fix I'm just using diffusers <0.12 which works 

![Screenshot 2023-01-26 at 4 20 20 PM](https://user-images.githubusercontent.com/826261/214980779-c173b893-b56b-4f63-839d-f51a245729cf.png)

**Comment by teticio** [comment]
Thanks for bringing this to my attention. Should be fixed now.
