### ISSUE TITLE
Diffusers v0.12 removed the `ema_model.averaged_model` attribute

### ISSUE THREAD

**Issue by shiehn** [teticio/audio-diffusion#24]
Diffusers v0.12 removed the `ema_model.averaged_model` attribute which is referenced in train_unet.py

![0](https://user-images.githubusercontent.com/826261/216298676-a6d088cb-2261-4f62-98e6-4d3ece80fc47.png)
![Screenshot 2023-02-02 at 1 46 24 AM](https://user-images.githubusercontent.com/826261/216298689-0a88e324-13f1-42d5-9b02-7eaa5f44ccba.png)

**Comment by teticio** [comment]
Thanks again! Fixed it.
