### ISSUE TITLE
Increasing input size

### ISSUE THREAD

**Issue by ST2-EV** [teticio/audio-diffusion#25]
Have you tried doing it with samples larger than 5 seconds., if so what is the memory requirement for something like that?

**Comment by shiehn** [comment]
I've been generating clips ~11s at 44.1k and the GPU is spiking around 27GB. I had to set the batch size etc to low numbers which translates to very slow training times.

**Comment by ST2-EV** [comment]
oof that is a lot, when you create the mel spectograms, do you have to manually chop up your dataset into 11 second clips or does the script do that for you? Also what resolution is your 11 second clip mel spectogram? thanks so much for the quick response

**Comment by shiehn** [comment]
(disclaimer: I not an expert I've just been experimenting) 

I did not change the size of the source audio but I noticed increasing the X axis in the mel specs increased the output length.  I was using powers of 2 to be safe.  

side-note: Google Colab pro subscription will let you access GPUs up to 40GBs

**Comment by ST2-EV** [comment]
okay yeah that's good to know...thanks
