### ISSUE TITLE
how does the audio_to_images.py file work?

### ISSUE THREAD

**Issue by ST2-EV** [teticio/audio-diffusion#27]
does it chop up the audio samples to 5 second clips, so if i put multiple hour long clips, it will automatically split it into 5 second clips?

**Comment by teticio** [comment]
Yes. Or if the mel parameters are changed, instead of 5 second samples, it will be a different length.

**Comment by ST2-EV** [comment]
thanks and how is it split? like first 5 seconds is one sample, then the next 5, etc?

**Comment by teticio** [comment]
Exactly. There is an index stored, which goes from 0 to the number of
samples in each file.
