### ISSUE TITLE
Whether the longer music sample is the repetition of a shorted sample?

### ISSUE THREAD

**Issue by gandolfxu** [teticio/audio-diffusion#28]
I have found that the generated music sample repeats every few seconds.
Does the loop mean repetition？

Can this model generate natural long music?

**Comment by teticio** [comment]
Each music sample corresponds to an image, so the length of the sample can be thought of as the x-resolution. This is limited by the GPU memory you have available. As it stands it is limite to short samples of a few seconds, but there are ways to stitch these samples together, which are explored in the sample notebooks. The idea of this repo was to show what could be done with a single commercial grade GPU: hopefully someone with access to much more compute power can do something more impressive.
