### ISSUE TITLE
AttributeError: 'AutoencoderKL' object has no attribute 'sample_size'

### ISSUE THREAD

**Issue by AIWithShrey** [teticio/audio-diffusion#36]

**Comment by teticio** [comment]
Please give some details about what you were doing to get this error.

**Comment by Leezp99** [comment]
i also meet this situation by using the following code

accelerate launch --config_file config/accelerate_local.yaml scripts/train_unet.py --dataset_name data_all/iemocap_256 --hop_length 1024 --output_dir models/ddpm-ema-audio-256-iemocap --train_batch_size 16 --num_epochs 100 --gradient_accumulation_steps 1 --learning_rate 1e-4 --lr_warmup_steps 500 --mixed_precision no --vae teticio/latent-audio-diffusion-256

**Comment by teticio** [comment]
Thanks! I have fixed this now. Please let me know if this works for you.
