### ISSUE TITLE
multi-gpu training

### ISSUE THREAD

**Issue by bluer555** [teticio/audio-diffusion#38]
Wondering how to train the model with multiple gpus? Thanks! (I'm new to the pytorch lightning)

**Comment by teticio** [comment]
The VAE model is trained with pytorch lightning. The way to train with multiple gpus is specify the number of devices in the ldm_autoencoder_kl.yaml config file.

The UNET model is trained with accelerate (Hugging Face). In this case you can configure this with accelerate config or editing accelerate_local.yaml
