### ISSUE TITLE
do you think this could be used for timbre transfer?

### ISSUE THREAD

**Issue by johndpope** [teticio/audio-diffusion#4]
like this - but instead of using pix2pix 
https://github.com/hmartelb/Pix2Pix-Timbre-Transfer

**Comment by teticio** [comment]
I've just updated the test_model.ipynb notebook to allow generation of audios from other audios (like having a starting image). You can use it to "remix" an existing track with some interesting results. Thanks for the Pix2Pix link - looks interesting. It is probably better at doing it as it was specifically trained to do that. This model is good at generating plausible samples from its knowledge of what they "look" like, but it hasn't been trained on pairs of samples (think of style GANS trained on horses and zebras that learn to convert between them).
