### ISSUE TITLE
whats the difference between 256 and 512 dataset

### ISSUE THREAD

**Issue by sankar-mukherjee** [teticio/audio-diffusion#41]
whats the difference between these two datasets, other than no of examples.

https://huggingface.co/datasets/teticio/audio-diffusion-256
https://huggingface.co/datasets/teticio/audio-diffusion-512

Both have the same descriptions

x_res = 256
y_res = 256
sample_rate = 22050
n_fft = 2048
hop_length = 512

https://huggingface.co/datasets/teticio/audio-diffusion-512 should be 
x_res = 512
y_res = 512

or i am missing something?

**Comment by teticio** [comment]
Thanks - fixed it!
