### ISSUE TITLE
Duration of generated audio

### ISSUE THREAD

**Issue by drizzle0171** [teticio/audio-diffusion#42]
Hi, I tried to train the VAE with my own audio dataset.
But when I generated some audio by the my model, it only generates 3-second audio file even though origin audio was 26 seconds.
How can I solve this problem?

**Comment by teticio** [comment]
The way it works is to convert your music into images. The resolution of the images is limited by the size of your GPU and determines the quality and length of the generations. It automatically slices your training audio into samples according to the resolution and sample rate you select. There are ways to stitch samples together.

**Comment by drizzle0171** [comment]
I missed the message! Thank you for answering! :) May I know you what image size you use when you train the demo? I have many GPUs such as A100, A6000, RTX 3090, 2080 so can you tell me what size is best for me?

**Comment by drizzle0171** [comment]
By the way, I have a one more question! :) The photo is my audio VAE model which trained with the given ldm_autoencoder_kl.yaml. As you can see, the value of the KL divergence was increased until 600 ...! Is there anything that I missed? I really want to know the factor of this situation. Thank you for reading my questions.

<img width="1556" alt="image" src="https://github.com/teticio/audio-diffusion/assets/90444862/b1e96670-1ac0-4bfd-bc92-d177bb2ed631">

**Comment by teticio** [comment]
Have a look at the tensorboards of the models I have trained - that might give you a hint. https://huggingface.co/teticio/latent-audio-diffusion-256/tensorboard

Regarding size - I'd recommend doing a test with one mp3 and one epoch, say, and seeing how big a batch size you can fit on your rig and how long it takes per step. Of course, the big unknown is how long to run the training for and that will depend on your dataset (how heterogenous it is, etc).
