### ISSUE TITLE
Request ... No GUI ???

### ISSUE THREAD

**Issue by kalle07** [teticio/audio-diffusion#47]

**Comment by teticio** [comment]
There is this... https://huggingface.co/spaces/teticio/audio-diffusion

**Comment by kalle07** [comment]
i see  THX,

is it also all offline possible  without colab ?

**Comment by teticio** [comment]
Sure, but you will need a GPU or lots of patience. You can run the app.py file locally.

**Comment by kalle07** [comment]
i have an RTX ....
in your describtion i dont see wat exactly i should install and which models i should copy in which folder...
and i only want create audio from text-prompts
app.py its starts localhost on a spezific port ?

**Comment by teticio** [comment]
It doesn't work with text prompts. Gradio runs on port 7860 by default. It will download the models for you. There is a requirements.txt file so "pip install -r requiirements.txt"

**Comment by kalle07** [comment]
i see .. may i try   ;)
