### ISSUE TITLE
Errors running the notebooks in Colab

### ISSUE THREAD

**Issue by DCooper-nz** [teticio/audio-diffusion#49]
I get these errors whenever I try to run the first cell of any of the notebooks on Colab, in this case it was 'train_model.ipynb'

  Building wheel for audiodiffusion (pyproject.toml) ... done
  Building wheel for ffmpy (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 16.1.0 which is incompatible.
google-colab 1.0.0 requires requests==2.31.0, but you have requests 2.32.3 which is incompatible.
ibis-framework 8.0.0 requires pyarrow<16,>=2, but you have pyarrow 16.1.0 which is incompatible.

I am just opening it and hitting run, is there something else I need to do? Cheers.

**Comment by teticio** [comment]
Thanks for flagging this. I have fixed it so it should work now.
