### ISSUE TITLE
How long does it take for the model to converge after training?

### ISSUE THREAD

**Issue by 980202006** [teticio/audio-diffusion#5]
I want to train this model on my own dataset, how long does it take for the model to converge?

**Comment by teticio** [comment]
Hi. You can see the tensorboard here https://huggingface.co/teticio/audio-diffusion-instrumental-hiphop-256/tensorboard, for example, and see the loss curves and generated audios along the way. It already generates decent results after 10 epochs, which takes about 12 hours on my RTX 2080 Ti with this dataset of around 30,000 samples.
