### ISSUE TITLE
Training with size 64 works. Training with size 256 does not yield good results.

### ISSUE THREAD

**Issue by AI-Guru** [teticio/audio-diffusion#7]
Hi!

I am digging deeper and finding a lot of insights! 

I did two trainings on the same dataset. The dataset has roundabout 140 samples. This dataset is rather small. It is for me to get started.

Training with image size 64 yields some promising results. A model trained on image size 256 yields only noise. Here is a comparison:
<img width="1107" alt="grafik" src="https://user-images.githubusercontent.com/32195399/193085669-d1c0b5b8-e1e3-4ae7-a562-2cc574452f4a.png">

The loss curves look normal.

Any ideas?

Working with your repo is fantastic!

Best,
Tristan

**Comment by AI-Guru** [comment]
My bad.

It turns out that I blindly did another change, when moving from 64 to 256. I set the training mode to distributed on two GPUs. Have to look more into that.

I am currently training on a single GPU works!

**Comment by 980202006** [comment]
![image](https://user-images.githubusercontent.com/24452502/201895268-31597904-9e7b-4143-845e-ed682375b17e.png)
![image](https://user-images.githubusercontent.com/24452502/201895353-6e331044-0d46-40ec-8b40-3be9a4086216.png)

**Comment by 980202006** [comment]
I use from_pretrained to reload the model, but it fails, the loss does not start from 0.04, but from 1.2.
