### ISSUE TITLE
Diffusion steps 1000.

### ISSUE THREAD

**Issue by AI-Guru** [teticio/audio-diffusion#8]
Hi! 

I wonder why you set the number of diffusion steps to 1000. Could it be too big or too small?

Best,
Tristan

**Comment by teticio** [comment]
It is the default setting in the diffusers library - in fact it is somewhat hardwired for inference. I now provide a way to change the number of stpes in inference, but it is best to train / infer using the same number of steps. I haven't experimented with training with different numbers, but I have noticed that every so often the modek doesn't converge in inference and produces a noisy sample, so I would hypothesise that 1000 is not enough.
